# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  name: build-and-test
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Install dependencies
        cammand: |
          apk add --no-cache py-pip=9.0.0-r1
          pip intall docker-compose==1.15.0
      - run:
        name: Run tests
        command: |
          docker-compose up -d
          docker-compose run dockerapp python test.py

workflows:
  jobs:
    build-and-test